586: Når flere meldinger på samme deltaker, så kan de bli konsumert i…
navikt/amt-arena-acl pull request #111
Opened 2022-11-17 07:48 UTC by magnusev

… feil rekkefølge

2022-11-17 10:00 UTC, AlexGaard commented on src/main/kotlin/no/nav/amt/arena/acl/domain/db/ArenaDataDbo.kt
> +	NEWER_MESSAGE_RECEIVED
Hadde QUEUED vært et bedre navn, slik som i fiksen til DAB?

2022-11-17 10:05 UTC, AlexGaard requested changes
Dette vil kun sette status på meldinger slik at de ikke plukkes opp av retry handleren, men det vil ikke sette status tilbake fra NEWER_MESSAGE_RECEIVED -> RETRY etter en melding med status RETRY er konsumert

2022-12-13 08:41 UTC, AlexGaard commented on src/main/kotlin/no/nav/amt/arena/acl/repositories/ArenaDataRepository.kt
> +	fun updateIngestStatus(ids: Set<Int>, ingestStatus: IngestStatus) {
Anbefaler early return hvis listen er tom, ellers så krasjer det.

2023-01-04 08:06 UTC, AlexGaard requested changes

2023-01-04 08:06 UTC, AlexGaard commented on src/main/kotlin/no/nav/amt/arena/acl/services/ArenaMessageProcessorService.kt
> +
Dette løser egentlig ikke behovet til oppgaven. Vi må stoppe meldingen hvis det finnes eldre meldinger liggende.

2023-01-04 08:07 UTC, AlexGaard commented
Når vi hopper over til å hente data fra VALP så trengs egentlig ikke denne oppgaven lenger siden vi kan bruke common kafka-retry, foreslår at vi kanskje legger den på is siden den medfører ekstra kompleksitet.

2023-01-20 13:12 UTC, izisfro reviewed
Kunne det vært en enklere løsning om man
1. Hente distinct arenaid+table name og sortere på eldste dato først i retry processor OG
2. Når vi får nye meldinger, sjekk om det finnes en eldre meldinger med status retry, isåfall legg meldingen rett til retry uten å ingeste så steg 1 vil sørge for at den havner bakerst

2023-01-24 16:02 UTC, closed without merging