Send gjennomforing når sak konsumeres
navikt/amt-arena-acl pull request #76
Opened 2022-06-24 10:36 UTC by izisfro

2022-06-24 12:04 UTC, AlexGaard commented on src/main/kotlin/no/nav/amt/arena/acl/repositories/ArenaGjennomforingRepository.kt
> +	fun get(id: UUID) : AmtGjennomforing? {
Hvis man spørr med en UUID så ville jeg tro at det er en feil hvis man ikke finner noe data og at man heller burde kaste et exception

2022-06-24 12:12 UTC, AlexGaard requested changes

2022-06-24 12:12 UTC, AlexGaard commented on src/main/resources/db/migration/V05__arena-gjennomforing.sql
> +        tiltak_kode             VARCHAR                 NOT NULL,
Tror kanskje jeg ville denormalisert databasen litt ved å droppe tiltak_navn og tiltak_kode siden de allerede finnes i arena_tiltak tabellen.

2022-06-24 12:12 UTC, AlexGaard commented on src/main/kotlin/no/nav/amt/arena/acl/repositories/ArenaGjennomforingRepository.kt
> +		AmtGjennomforing(
Jeg tror kanskje jeg ville laget en egen DBO for å representere gjennomføringen i databasen

2022-06-24 12:12 UTC, AlexGaard commented on src/main/kotlin/no/nav/amt/arena/acl/repositories/ArenaGjennomforingRepository.kt
> +	fun upsert(arenaSakId: Long?, gjennomforing: AmtGjennomforing) {
Det kan hende at det hadde vært bedre med en upsert dto istedenfor

2022-06-27 08:27 UTC, AlexGaard commented on src/main/kotlin/no/nav/amt/arena/acl/utils/RowMapperExtensionFunctions.kt
> +}
Man trenger egentlig ikke å mappe om noe her, det holder å bruke `return this.getLong(columnLabel)`

2022-06-27 08:28 UTC, AlexGaard commented on src/main/kotlin/no/nav/amt/arena/acl/utils/RowMapperExtensionFunctions.kt
> +fun ResultSet.getInteger(columnLabel: String): Int? {
Burde denne hete `getNullableInteger`?

2022-06-27 08:29 UTC, AlexGaard approved these changes

2022-06-27 08:33 UTC, izisfro commented on src/main/kotlin/no/nav/amt/arena/acl/utils/RowMapperExtensionFunctions.kt
> +fun ResultSet.getInteger(columnLabel: String): Int? {
Tanken var at ved å kalle det Integer så vet man at den er nullable, men jeg kan godt rename

2022-06-30 07:48 UTC, merged